title: Nícolas Tarzia
email: contato@nicolastarzia.com
markdown: kramdown
theme: dev-blog-theme
url: https://nicolastarzia.com

############################################################
# Allow comments using Azure Functions
emptyArray: [] #
comments:
  receiver: https://c0m3nt4r10.azurewebsites.net/api/PostComment
############################################################

azure_insights: e8216e39-8719-46cf-beba-d05a71693e6e

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
paginate: 5
############################################################


authors:
  nicolastarzia:
    name: Nicolas Tarzia
    email: nicolastarzia@gmail.com
    url: https://nicolastarzia.com

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: nicolastarzia
      commenting: open
  -
    scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      author: nicolastarzia
      commenting: open

devblog:
  date_format: "%b %-d, %Y"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap
 - jemoji
