## Basic Configuration
baseurl = "https://nicolastarzia.com/"

title = "Nicolas Tarzia"
theme = "hansolo"

enableRobotsTXT = true
postNavigation = true
relatedPosts = true
enableEmoji = true

## Site Settings
[[menu.main]]
    name = "Sobre"
    identifier = "about"
    weight = 300
    url = "/about/"
