## Basic Configuration
baseurl = "https://nicolastarzia.com/"
languageCode = "pt"

title = "Nicolas Tarzia"
theme = "hyde-hyde"

## Hugo Built-in Features
#disqusShortname = "nicolastarzia"
#googleAnalytics = "UA-42627965-1"
enableRobotsTXT = true
postNavigation = true
relatedPosts = true
enableEmoji = true

## Site Settings
[params]
    author = "Nícolas Tarzia"
    title = "Desenvolvedor"
    description = "desenvolvimento, arquitetura de software e algumas outras coisas"
    authorimage = "/img/avatar.jpeg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "nicolastarzia"
    instagram = "nicolastarzia"
    linkedin = "nicolastarzia"
    twitter = "nicolastarzia"
    facebook = "nicolastarzia"
    stackoverflow = "nicolastarzia"
    telegram = "nicolastarzia"
    email = "nicolastarzia@gmail.com"

## Main Menu
#[[menu.main]]
#    name = "Posts"
#    weight = 100
#    identifier = "posts"
#    url = "/posts/"
[[menu.main]]
    name = "Sobre"
    identifier = "about"
    weight = 300
    url = "/about/"
